export const signUp='/signup'
export const signIn='/signin'
export const cart='/cart'
export const signOut='/signout'
export const account='/account'
export const landing='/'
export const forgetPassword='/pchange'
export const Item='/item'